### PR TITLE
Use XConfigureWindow for resize implementation

### PR DESCRIPTION
**Pull request by DeltaEvo**
Old implementation didn't work in i3 (and I think some other tilling WM too)

### CODE REVIEW

**Comment by AndreyBelym** [comment]
Hi @DeltaEvo! Really thank you for the patch. However, I think we should check if window manager supports resizing before calling `XConfigureWindow`, because it is quite low-level function.

**Comment by DeltaEvo** [comment]
How do you check a such thing ?
PS: xdotool dosen't seem to do a check https://github.com/jordansissel/xdotool/blob/master/xdo.c#L291

**Comment by AndreyBelym** [comment]
The `_NET_SUPPORTED` property contains a list with all supported atoms, including `_NET_MOVERESIZE_WINDOW`. Looks like [_xdo_ewmh_is_supported](https://github.com/jordansissel/xdotool/blob/master/xdo.c#L1477) does this in xdotool.

**Comment by AndreyBelym** [comment]
Thank you for your contribution. However, it's better to resize windows via a window manager if it supports this functionality. We can't call low-level `X11` functions in all cases since it can cause conflicts with a window manager.

**Pull request closed without merging**
