### PR TITLE
[WIP] Implement functional testing (closes #67)

### LINKED ISSUE #67: Implement automated testing
We can use Travis CI for testing on Linux and [macOS](https://docs.travis-ci.com/user/osx-ci-environment/), and [AppVeyour](https://www.appveyor.com/) for testing on Windows. 
- [ ] Windows
- [ ] macOS
- [ ] Linux

### PR DESCRIPTION
**Pull request by AndreyBelym**

### CODE REVIEW

**Comment by inikulin** [comment]
Why close?

**Comment by AndreyBelym** [comment]
`

**Comment by AndreyBelym** [comment]
Just got some thought and wanted to test it. 

BTW, can you add the AppVeyor webhook, please? It's Windows CI, free for opensource repos.
URL: 
https://ci.appveyor.com/api/github/webhook?id=xdacywoetdk7s7bt

Content Type:
application/x-www-form-urlencoded

Which events would you like to trigger this webhook?
 - [x] Pull Request
 - [x] Push

**Comment by inikulin** [comment]
Please, ping once I'll be in the office. Also, AFAIR @churkin also has permissions to do this

**Comment by churkin** [comment]
done

**Comment by AndreyBelym** [comment]
Wow, thanks guys, it's awesome! :+1:

**Pull request closed without merging**
